apiVersion: v1
kind: Service
metadata:
  name: debezium-customer-service-service
  labels:
    app: debezium-customer-service
spec:
  selector:
    app: debezium-customer-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort