apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: debezium-customer-service
build:
  artifacts:
    - image: nivorbit/debezium-customer-service
      buildpacks:
        builder: gcr.io/buildpacks/builder:v1
manifests:
  rawYaml:
    - k8s/*